history/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('registration/', views.UserCreateView.as_view(),
        name='registration'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('password-change/', auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    path('logout/', auth_views.LogoutView.as_view(),
        name='logout')
]

history/history/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='home/')),
    path('home/', include('homepage.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

history/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.HomepageView.as_view(), name='index')
]

history/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('<slug:category_slug>/', views.PostListView.as_view(),
         name='posts_list'),
    path('<slug:category_slug>/<slug:post_slug>/', views.post_detail,
         name='post_detail')
]

history/accounts/models.py
from django.db import models

# Create your models here.

history/posts/models.py
from markdown import markdown

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField('Заголовок статьи', max_length=50)
    slug = models.SlugField('Слаг')
    content = models.TextField('Текст статьи')
    pub_date = models.DateField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(User, models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('Category', models.CASCADE,
            verbose_name='Категория')
    image = models.ImageField('Превью статьи', upload_to='article_images')

    class Meta:
        ordering = ['pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.content = markdown(self.content)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post_detail',
                args=[self.category.slug, self.slug])


class Category(models.Model):
    title = models.CharField('Название категории', max_length=50)
    slug = models.SlugField('Слаг')

    class Meta:
        ordering = ['title']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('posts:posts_list', args=[self.slug])

    def __str__(self):
        return self.title

history/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class WidgetAttrsMixin:
    def add_widget_attr(self, field, attr_name, value):
        field.widget.attrs[attr_name] = value


class UserForm(UserCreationForm, WidgetAttrsMixin):
    def get_initial_for_field(self, field, field_name):
        if field_name == 'username':
            self.add_widget_attr(field, 'placeholder', 'Your nickname')
        elif field_name == 'password1':
            self.add_widget_attr(field, 'placeholder', 'Your password')
        elif field_name == 'password2':
            self.add_widget_attr(field, 'placeholder',
                    'Confirm your password')

        super().get_initial_for_field(field, field_name)


class LoginForm(AuthenticationForm, WidgetAttrsMixin):
    def get_initial_for_field(self, field, field_name):
        if field_name == 'username':
            self.add_widget_attr(field, 'placeholder', 'Your nickname')
        elif field_name == 'password':
            self.add_widget_attr(field, 'placeholder', 'Your password')

        super().get_initial_for_field(field, field_name)

history/accounts/views.py
from django.urls import reverse
from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView

from .forms import UserForm, LoginForm

class UserCreateView(FormView):
    form_class = UserForm
    template_name = 'registration/registration.html'
    success_url = '/accounts/login/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class MyLoginView(LoginView):
    form_class = LoginForm

history/homepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from posts.models import Category


class HomepageView(TemplateView):
    template_name = 'homepage/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

history/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Post, Category


class PostListView(ListView):
    paginate_by = 25
    template_name = 'posts/index_page-categories.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category,
            slug=self.kwargs['category_slug'])
        return Post.objects.filter(category=self.category)


def post_detail(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug,
            category__slug=category_slug)
    return render(request, 'posts/index_page-article.html', {'post': post})

history/homepage/templates/homepage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'js/castom_events/load_screen.js' %}" defer></script>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
	<title>History</title>
    <script src="{% static 'libs/libs.min.js' %}" defer></script>
    <script src="{% static 'js/default_events/scripts-modules.min.js' %}" defer></script>
</head>
<body class="body_no-scroll">
	<div class="load-screen">
        <img src="{% static 'image/icons/load.svg' %}" alt="">
	</div>
	<div class="page page_brown page_h">
		<div class="menu">
		<nav class="page__aside-menu">
			<ul>
                {% for category in category_list %}
                    <a href="{{ category.get_absolute_url }}"><li>{{ category.title }}</li></a>
                {% endfor %}
			</ul>
		</nav>
		<div class="sidebar">
			<button class="sidebar__button" data-event="toggle_menu"></button>
            <a href="{% url 'accounts:registration' %}" class="sidebar__button" data-event="regestraiont-bar"></a>
			<a href="index.html" class="sidebar__root-link">H</a>
		</div>
	</div>
		<div class="page__content">
			<span class="page__text page__text_flex-column page__text_indent-p">	
				.history 
				<span class="page__text-anim-element">Write.Cloud.Learn
				</span>
			</span>
		</div>
	</div>
</body>
</html>

history/posts/templates/posts/index_page-categories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'js/castom_events/load_screen.js' %}" defer></script>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
	<title>Categories</title>
    <script src="{% static 'libs/libs.min.js' %}" defer></script>
    <script src="{% static 'js/default_events/scripts-modules.min.js' %}" defer></script>
</head>
<body class="body_white body_no-scroll">
	<div class="load-screen">
        <img src="{% static 'image/icons/load.svg' %}" alt="">
	</div>
	<header class="header">
		<div class="wrraper wrraper_flex-sb">
			<div class="header__functional">
				<a href="index.html">H</a>
				<button class="header__sort-button"></button>
			</div>
			<div class="header__search-block">
				<input name="search" type="text" placeholder="Search" class="header__search-input">
				<button class="header__push-search-button"></button>
			</div>
		</div>
	</header>
	<div class="page page_flex-center page_indent-p page_flex-column">
		<div class="wrraper wrraper_flex-column wrraper_relative-pos">
			<div class="page__counter-posts">

			</div>
			<div class="page__post-list page__post-list_indent">
                {% for post in post_list %}
				<div class="page__post-block">
					<div>
						<div class="page__animate-image">
                            <img src="{{ post.image.url }}" alt="" class="page__post-block-background">
						</div>
					</div>
					<div>
                        <a href="{{ post.get_absolute_url }}"><span class="page__main-value">{{ post.title }}</span></a>
                        <span>{{ post.content|safe|truncatewords:5 }}</span>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>
</body>
</html>

history/templates/homepage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'js/castom_events/load_screen.js' %}" defer></script>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
	<title>History</title>
    <script src="{% static 'libs/libs.min.js' %}" defer></script>
    <script src="{% static 'js/default_events/scripts-modules.min.js' %}" defer></script>
</head>
<body class="body_no-scroll">
	<div class="load-screen">
        <img src="{% static 'image/icons/load.svg' %}" alt="">
	</div>
	<div class="page page_brown page_h">
		<div class="menu">
		<nav class="page__aside-menu">
			<ul>
                {% for category in category_list %}
                    <a href="{{ category.get_absolute_url }}"><li>{{ category.title }}</li></a>
                {% endfor %}
			</ul>
		</nav>
		<div class="sidebar">
			<button class="sidebar__button" data-event="toggle_menu"></button>
            <a href="{% url 'login' %}" class="sidebar__button" data-event="regestraiont-bar"></a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="sidebar__button"></a>
            {% endif %}
            <a href="{% url 'homepage:index' %}" class="sidebar__root-link">H</a>
		</div>
	</div>
		<div class="page__content">
			<span class="page__text page__text_flex-column page__text_indent-p">	
				.history 
				<span class="page__text-anim-element">Write.Cloud.Learn
				</span>
			</span>
		</div>
	</div>
</body>
</html>

history/templates/new_templates/index_page-404.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="./css/style.min.css">
	<title>Document</title>
</head>
<body>
	<div class="container">
		<div class="container__error">
			<span>
				404
			</span>
			<span>
				error
			</span>	
		</div>
	</div>
</body>
</html>

history/templates/posts/index_page-article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'js/castom_events/load_screen.js' %}" defer></script>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
	<title>Article</title>
    <script src="{% static 'libs/libs.min.js' %}" defer></script>
    <script src="{% static 'js/default_events/scripts-modules.min.js' %}" defer></script>
</head>
<body class="body_white">
	<div class="load-screen">
        <img src="{% static 'image/icons/load.svg' %}" alt="">
	</div>
	<div class="page">
		<div class="wrraper wrraper_absolute-pos">
			<a href="index_page-categories.html" class="page__button-back">
				<img src="./image/icons/back.svg" alt="">
			</a>
		</div>
		<div class="page__article-panel">
			<div>
				<div>
                    <span>Author: {{ post.author.username }}</span>
                    <span>Time: {{ post.pub_date }}</span>
                    <span>Cat: {{ post.category.title }}</span>
				</div>
				<div class="page__copy">
					<button class="page__button-copy">Копировать Статью</button>
				</div>
			</div>
			<div class="page__main-text-article">
                <span class="page__index"><h1>{{ post.title }}</h1></span>
                <span>{{ post.content|safe }}</span>
			</div>
			<div>
				
			</div>
		</div>
	</div>
</body>
</html>

history/templates/posts/index_page-categories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'js/castom_events/load_screen.js' %}" defer></script>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
	<title>Categories</title>
    <script src="{% static 'libs/libs.min.js' %}" defer></script>
    <script src="{% static 'js/default_events/scripts-modules.min.js' %}" defer></script>
</head>
<body class="body_white body_no-scroll">
	<div class="load-screen">
        <img src="{% static 'image/icons/load.svg' %}" alt="">
	</div>
	<header class="header">
		<div class="wrraper wrraper_flex-sb">
			<div class="header__functional">
                <a href="{% url 'homepage:index' %}">H</a>
				<button class="header__sort-button"></button>
			</div>
			<div class="header__search-block">
				<input name="search" type="text" placeholder="Search" class="header__search-input">
				<button class="header__push-search-button"></button>
			</div>
		</div>
	</header>
	<div class="page page_flex-center page_indent-p page_flex-column">
		<div class="wrraper wrraper_flex-column wrraper_relative-pos">
			<div class="page__counter-posts">

			</div>
			<div class="page__post-list page__post-list_indent">
                {% for post in post_list %}
				<div class="page__post-block">
					<div>
						<div class="page__animate-image">
                            <img src="{{ post.image.url }}" alt="" class="page__post-block-background">
						</div>
					</div>
					<div>
                        <a href="{{ post.get_absolute_url }}"><span class="page__main-value">{{ post.title }}</span></a>
                        <span>{{ post.content|safe|truncatewords:5 }}</span>
					</div>
				</div>
                {% endfor %}
			</div>
            <div class="page__paginator">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="page__arrow-slide-page"><img src="./image/icons/back.svg" alt=""></a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="page__arrow-slide-page">{{ page_obj.previous_page_number }}</a>
                {% else %}
                    <span class="page__arrow-slide-page"><img src="./image/icons/back.svg" alt=""></span>
                {% endif %}

                <span>{{ page_obj.number }}</span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="page__arrow-slide-page"><img src="./image/icons/back.svg" alt=""></a>
                {% else %}
                    <span class="page__arrow-slide-page"><img src="./image/icons/back.svg" alt=""></span>
                {% endif %}
            </div>
		</div>
	</div>
</body>
</html>